name: Deploy Cloud Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTENV_PRIVATE_KEY_CI: ${{ secrets.DOTENV_PRIVATE_KEY_CI }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 'latest'

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build projects
        run: pnpm build

      - name: Deploy RSS Digester Cloud Function
        run: pnpm deploy:rss-digester

      - name: Deploy Batch Translator Cloud Function
        run: pnpm deploy:batch-translator

      - name: Deploy HTML to Markdown Converter Cloud Function
        run: pnpm deploy:html-to-markdown

      - name: Display Deployment Success
        run: echo "Cloud Functions deployment workflow completed successfully!"
